### ISSUE TITLE
Deploy abort/fail notification

### ISSUE THREAD

**Issue by mike-sheppard** [ItinerisLtd/trellis-slack-webhook-notify-during-deploy#10]
It'd be good to have a notification if the deployment fails/aborted by the user.

**Comment by tangrufus** [comment]
This is tricky with Trellis / Ansible. Ansible stops _immediately_ when encounters errors.

#### Possible solution A - Use `block` + `rescue`

Not excatly what we need - This is an example how we trigger rollback if deployments break `critical_urls`

```yaml
---
- import_playbook: deploy.yml

- hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"
  gather_facts: false
  tasks:
    - block:
        - uri:
            url: "https://{{ wordpress_sites[site].site_hosts[0].canonical }}{{ item }}?cache-busting={{ ansible_date_time.epoch }}"
          loop: "{{ wordpress_sites[site].critical_urls }}"
          connection: local
      rescue:
        - include_role: 
            name: rollback
        - fail:
            msg: "Critical urls are not 200 okay. Site rolled back"
```

#### Possible solution B - Use `handler`

Maybe. Needs more digging.

---

More on https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#handlers-and-failure

---

Do you have any solution in mind?
